import type { Metadata } from 'next'
import { Heebo, Lato } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import './globals.css'

const heebo = Heebo({
  variable: '--font-heebo',
  subsets: ['latin'],
})

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${lato.variable} ${heebo.variable} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='white'>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
